import type { Tier } from './types'

export type ResourceCategory = 'course' | 'youtube' | 'github' | 'paper'

export interface Resource {
  id: string
  title: { en: string; zh: string }
  description: { en: string; zh: string }
  url: string
  category: ResourceCategory
  tier: Tier
  free: boolean
  author?: string
}

export const resources: Resource[] = [
  // Courses - Top tier learning
  {
    id: 'fastai-practical-dl',
    title: { en: 'Practical Deep Learning for Coders', zh: '实用深度学习' },
    description: { en: 'Top-down approach to deep learning by Jeremy Howard and Rachel Thomas', zh: 'Jeremy Howard和Rachel Thomas的深度学习课程' },
    url: 'https://course.fast.ai/',
    category: 'course',
    tier: 'mid',
    free: true,
    author: 'fast.ai',
  },
  {
    id: 'deeplearning-ai-specialization',
    title: { en: 'Deep Learning Specialization', zh: '深度学习专项课程' },
    description: { en: 'Comprehensive specialization covering neural networks to deep learning by Andrew Ng', zh: 'Andrew Ng教授的综合深度学习专项课程' },
    url: 'https://www.deeplearning.ai/',
    category: 'course',
    tier: 'mid',
    free: false,
    author: 'DeepLearning.AI',
  },
  {
    id: 'huggingface-nlp-course',
    title: { en: 'Hugging Face NLP Course', zh: 'Hugging Face NLP课程' },
    description: { en: 'Complete course on NLP with transformers using Hugging Face library', zh: '使用Hugging Face库的完整NLP和Transformer课程' },
    url: 'https://huggingface.co/course',
    category: 'course',
    tier: 'mid',
    free: true,
    author: 'Hugging Face',
  },
  {
    id: 'harvard-cs50-ai',
    title: { en: 'CS50 AI with Python', zh: 'Harvard CS50 AI课程' },
    description: { en: 'Harvard\'s introduction to AI with Python by David Malan', zh: 'David Malan讲授的哈佛大学AI与Python入门课程' },
    url: 'https://cs50.harvard.edu/ai',
    category: 'course',
    tier: 'junior',
    free: true,
    author: 'Harvard University',
  },
  {
    id: 'stanford-cs229',
    title: { en: 'Stanford CS229: Machine Learning', zh: 'Stanford CS229：机器学习' },
    description: { en: 'Advanced machine learning course covering theory and applications', zh: '覆盖理论和应用的高级机器学习课程' },
    url: 'http://cs229.stanford.edu/',
    category: 'course',
    tier: 'senior',
    free: true,
    author: 'Stanford University',
  },
  {
    id: 'andrew-ng-ml-course',
    title: { en: 'Machine Learning Course', zh: '吴恩达机器学习课程' },
    description: { en: 'Foundational ML course covering supervised/unsupervised learning by Andrew Ng', zh: '吴恩达的机器学习基础课程' },
    url: 'https://www.coursera.org/learn/machine-learning',
    category: 'course',
    tier: 'junior',
    free: false,
    author: 'Andrew Ng',
  },

  // YouTube Channels
  {
    id: 'andrej-karpathy-makemore',
    title: { en: 'Andrej Karpathy makemore', zh: 'Andrej Karpathy makemore系列' },
    description: { en: 'Building neural networks from scratch with educational clarity', zh: '从零开始构建神经网络的教育性讲解' },
    url: 'https://www.youtube.com/playlist?list=PLAqhIrZiCoo0NV_qnZQ_-OsWAKMu2DQfj',
    category: 'youtube',
    tier: 'mid',
    free: true,
    author: 'Andrej Karpathy',
  },
  {
    id: 'andrej-karpathy-nanoGPT',
    title: { en: 'Andrej Karpathy nanoGPT', zh: 'Andrej Karpathy nanoGPT系列' },
    description: { en: 'Building a character-level language model and GPT from scratch', zh: '从零开始构建GPT和字符级语言模型' },
    url: 'https://www.youtube.com/watch?v=kCc8FmoeKS8',
    category: 'youtube',
    tier: 'senior',
    free: true,
    author: 'Andrej Karpathy',
  },
  {
    id: '3b1b-neural-networks',
    title: { en: '3Blue1Brown Neural Networks', zh: '3Blue1Brown神经网络系列' },
    description: { en: 'Visual introduction to neural networks and backpropagation', zh: '神经网络和反向传播的可视化介绍' },
    url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi',
    category: 'youtube',
    tier: 'junior',
    free: true,
    author: '3Blue1Brown',
  },
  {
    id: 'yannic-kilcher-papers',
    title: { en: 'Yannic Kilcher Paper Reviews', zh: 'Yannic Kilcher论文讲解' },
    description: { en: 'Deep dives into cutting-edge ML and NLP papers', zh: '深入讲解最新ML和NLP论文' },
    url: 'https://www.youtube.com/@YannicKilcher',
    category: 'youtube',
    tier: 'senior',
    free: true,
    author: 'Yannic Kilcher',
  },
  {
    id: 'two-minute-papers',
    title: { en: 'Two Minute Papers', zh: 'Two Minute Papers' },
    description: { en: 'Concise summaries of AI research papers and breakthroughs', zh: 'AI研究论文和突破的简洁总结' },
    url: 'https://www.youtube.com/@TwoMinutePapers',
    category: 'youtube',
    tier: 'junior',
    free: true,
    author: 'Two Minute Papers',
  },
  {
    id: 'sentdex-tutorials',
    title: { en: 'Sentdex Machine Learning', zh: 'Sentdex机器学习' },
    description: { en: 'Practical ML tutorials with scikit-learn, TensorFlow, and more', zh: '使用scikit-learn、TensorFlow等的实用ML教程' },
    url: 'https://www.youtube.com/@sentdex',
    category: 'youtube',
    tier: 'junior',
    free: true,
    author: 'Sentdex',
  },

  // GitHub Repositories
  {
    id: 'karpathy-nanoGPT',
    title: { en: 'karpathy/nanoGPT', zh: 'karpathy/nanoGPT' },
    description: { en: 'Minimal, clean implementation of GPT in PyTorch', zh: 'PyTorch中最小、干净的GPT实现' },
    url: 'https://github.com/karpathy/nanoGPT',
    category: 'github',
    tier: 'mid',
    free: true,
    author: 'Andrej Karpathy',
  },
  {
    id: 'rasbt-llms-from-scratch',
    title: { en: 'rasbt/LLMs-from-scratch', zh: 'rasbt/LLMs-from-scratch' },
    description: { en: 'Building LLMs from scratch with detailed implementations and explanations', zh: '从零开始构建LLM的详细实现和解释' },
    url: 'https://github.com/rasbt/LLMs-from-scratch',
    category: 'github',
    tier: 'senior',
    free: true,
    author: 'Sebastian Raschka',
  },
  {
    id: 'huggingface-transformers',
    title: { en: 'huggingface/transformers', zh: 'huggingface/transformers' },
    description: { en: 'State-of-the-art NLP, vision, and multimodal transformers library', zh: '最先进的NLP、视觉和多模态Transformer库' },
    url: 'https://github.com/huggingface/transformers',
    category: 'github',
    tier: 'mid',
    free: true,
    author: 'Hugging Face',
  },
  {
    id: 'geohot-tinygrad',
    title: { en: 'geohot/tinygrad', zh: 'geohot/tinygrad' },
    description: { en: 'Minimal deep learning framework for understanding ML fundamentals', zh: '用于理解ML基础的最小化深度学习框架' },
    url: 'https://github.com/geohot/tinygrad',
    category: 'github',
    tier: 'senior',
    free: true,
    author: 'George Hotz',
  },
  {
    id: 'microsoft-deepspeed',
    title: { en: 'microsoft/DeepSpeed', zh: 'microsoft/DeepSpeed' },
    description: { en: 'Library for efficient distributed training and inference at scale', zh: '用于高效分布式训练和大规模推理的库' },
    url: 'https://github.com/microsoft/DeepSpeed',
    category: 'github',
    tier: 'senior',
    free: true,
    author: 'Microsoft',
  },
  {
    id: 'pytorch-pytorch',
    title: { en: 'pytorch/pytorch', zh: 'pytorch/pytorch' },
    description: { en: 'Open-source machine learning framework with strong GPU support', zh: '具有强大GPU支持的开源机器学习框架' },
    url: 'https://github.com/pytorch/pytorch',
    category: 'github',
    tier: 'mid',
    free: true,
    author: 'Meta',
  },

  // Papers
  {
    id: 'attention-is-all-you-need',
    title: { en: 'Attention Is All You Need', zh: '《注意力机制就是一切》' },
    description: { en: 'Foundational Transformer paper by Vaswani et al. - introduced self-attention', zh: 'Vaswani等人的基础Transformer论文 - 引入自注意力' },
    url: 'https://arxiv.org/abs/1706.03762',
    category: 'paper',
    tier: 'mid',
    free: true,
    author: 'Vaswani et al.',
  },
  {
    id: 'lora-paper',
    title: { en: 'LoRA: Low-Rank Adaptation', zh: 'LoRA：低秩适配' },
    description: { en: 'Parameter-efficient fine-tuning with low-rank matrices', zh: '使用低秩矩阵的参数高效微调方法' },
    url: 'https://arxiv.org/abs/2106.09685',
    category: 'paper',
    tier: 'mid',
    free: true,
    author: 'Hu et al.',
  },
  {
    id: 'qlora-paper',
    title: { en: 'QLoRA: Quantized LoRA', zh: 'QLoRA：量化LoRA' },
    description: { en: 'Quantized low-rank adaption for efficient fine-tuning', zh: '用于高效微调的量化低秩适配' },
    url: 'https://arxiv.org/abs/2305.14314',
    category: 'paper',
    tier: 'senior',
    free: true,
    author: 'Dettmers et al.',
  },
  {
    id: 'dpo-paper',
    title: { en: 'Direct Preference Optimization', zh: '直接偏好优化(DPO)' },
    description: { en: 'Align language models directly without reward model training', zh: '无需奖励模型的直接语言模型对齐方法' },
    url: 'https://arxiv.org/abs/2305.18290',
    category: 'paper',
    tier: 'senior',
    free: true,
    author: 'Rafailov et al.',
  },
  {
    id: 'instructgpt-paper',
    title: { en: 'InstructGPT: Aligning with Instructions', zh: 'InstructGPT：指令对齐' },
    description: { en: 'RLHF approach for aligning language models to human instructions', zh: '通过RLHF对齐语言模型到人类指令的方法' },
    url: 'https://arxiv.org/abs/2203.02155',
    category: 'paper',
    tier: 'senior',
    free: true,
    author: 'Ouyang et al.',
  },
  {
    id: 'flash-attention-2',
    title: { en: 'FlashAttention-2: Faster Attention', zh: 'FlashAttention-2：更快的注意力' },
    description: { en: 'Fast and memory-efficient exact attention algorithm', zh: '快速和内存高效的精确注意力算法' },
    url: 'https://arxiv.org/abs/2307.08691',
    category: 'paper',
    tier: 'senior',
    free: true,
    author: 'Dao et al.',
  },
  {
    id: 'scaling-laws',
    title: { en: 'Scaling Laws for Neural Language Models', zh: '神经语言模型缩放定律' },
    description: { en: 'Empirical laws relating model scale, data, and compute to performance', zh: '模型规模、数据和计算与性能的经验关系' },
    url: 'https://arxiv.org/abs/2001.08361',
    category: 'paper',
    tier: 'senior',
    free: true,
    author: 'Kaplan et al.',
  },
  {
    id: 'rlhf-paper',
    title: { en: 'Learning from Human Preferences (RLHF)', zh: '从人类偏好学习(RLHF)' },
    description: { en: 'Reinforcement learning from human feedback methodology', zh: '从人类反馈学习的强化学习方法' },
    url: 'https://arxiv.org/abs/1909.08383',
    category: 'paper',
    tier: 'senior',
    free: true,
    author: 'Stiennon et al.',
  },
]
